LEGO/AsyncAPI.NET

src/LEGO.AsyncAPI.Readers/AsyncApiReaderSettings.cs, src/LEGO.AsyncAPI/Models/AsyncApiBindings.cs, src/LEGO.AsyncAPI/Models/AsyncApiChannel.cs, src/LEGO.AsyncAPI/Models/AsyncApiComponents.cs, src/LEGO.AsyncAPI/Models/AsyncApiCorrelationId.cs, src/LEGO.AsyncAPI/Models/AsyncApiDocument.cs, src/LEGO.AsyncAPI/Models/AsyncApiMessage.cs, src/LEGO.AsyncAPI/Models/AsyncApiMessageTrait.cs, src/LEGO.AsyncAPI/Models/AsyncApiOperationTrait.cs, src/LEGO.AsyncAPI/Models/AsyncApiParameter.cs, src/LEGO.AsyncAPI/Models/AsyncApiSchema.cs, src/LEGO.AsyncAPI/Models/AsyncApiServer.cs, src/LEGO.AsyncAPI/Models/AsyncApiServerVariable.cs, src/LEGO.AsyncAPI/Models/Bindings/Http/HttpMessageBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Http/HttpOperationBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Kafka/KafkaChannelBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Kafka/KafkaMessageBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Kafka/KafkaOperationBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Kafka/KafkaServerBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Pulsar/PulsarChannelBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/Pulsar/PulsarServerBinding.cs, src/LEGO.AsyncAPI/Models/Bindings/WebSockets/WebSocketsChannelBinding.cs, src/LEGO.AsyncAPI/Services/AsyncApiReferenceResolver.cs, src/LEGO.AsyncAPI/Writers/AsyncApiWriterSettings.cs, test/LEGO.AsyncAPI.Tests/Models/AsyncApiSchema_Should.cs
Dependency resolution is now enforced during writing depending on the writer settings.
Before you had to specifically call "ResolveReferences()".
This enables a slightly easier usecase, where you can create an object model of references, and still get a document out that matches the writer settings.
Payload has been added as a "Reference" type, as it should have been all along.
Payload sub references, now resolve correctly as well.
Using default setting (`ReferenceInlineSetting.DoNotInlineReferences`)
will yield the following output
``` yaml
channels:
mychannel:
publish:
message:
payload:
type: object
required:
- testB
properties:
testC:
$ref: '#/components/schemas/testC'
testB:
$ref: '#/components/schemas/testB'
components:
schemas:
testD:
type: string
format: uuid
testC:
type: object …
```
=> fix: payload schema reference resolution

src/LEGO.AsyncAPI.Readers/AsyncApiYamlDocumentReader.cs, src/LEGO.AsyncAPI.Readers/V2/AsyncApiDeserializer.cs, src/LEGO.AsyncAPI.Readers/V2/AsyncApiSchemaDeserializer.cs, test/LEGO.AsyncAPI.Tests/AsyncApiDocumentV2Tests.cs, test/LEGO.AsyncAPI.Tests/AsyncApiReaderTests.cs
To better enable extension validation, any thrown `AsyncApiExceptions` during ExtensionParsing, will be pushed to the diagnostics Errors list.
=> chore: add ability to throw AsyncApiExceptions during extension parsing

src/LEGO.AsyncAPI.Readers/V2/AsyncApiSchemaDeserializer.cs, test/LEGO.AsyncAPI.Tests/Models/AsyncApiSchema_Should.cs
Additional properties field of the async spec were experiencing a bug. Having the "additionalProperties" present caused the library to throw an Error as the MapNode didn't implement GetBooleanValueOrDefault and the code thus defaulted to the abstract ParseNode implementation which throw an exception.
This PR tries to cast the node to a ValueNode before calling GetBooleanValueOrDefault else the already existing behaviour.
Unit test to accommodate the change.
- Add: Fixed bug causing additionalProperties to cause an Error.
- Remove: Removed bug causing additionalProperties to cause an Error.
=> fix: async schema deserializer "additionalProperties" not deserializing JsonSchema correctly

src/LEGO.AsyncAPI.Readers/V2/AsyncApiSchemaDeserializer.cs, test/LEGO.AsyncAPI.Tests/Models/AsyncApiSchema_Should.cs
Accept the `const` keyword for the `schema` object. See full definition [here](https://www.asyncapi.com/docs/reference/specification/v2.3.0#schema).
- Add: const to `AsyncApiSchemaDeserializer`
- Add: some tests
=> fix: parse const keyword in a schema object

src/LEGO.AsyncAPI.Bindings/Sqs/Queue.cs, src/LEGO.AsyncAPI.Bindings/Sqs/SqsChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Sqs/SqsOperationBinding.cs, test/LEGO.AsyncAPI.Tests/Bindings/Sqs/SqsBindings_should.cs
This PR adds the missing properties required to enable high throughput on a FIFO queue. The two properties are deduplicationScope and fifoThroughputLimit. As outlined in the AWS documentation - https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/high-throughput-fifo.html#enable-high-throughput-fifo.
I have raised a PR on the AsyncAPI binding repo which has been approved and is awaiting merge - https://github.com/asyncapi/bindings/pull/216.
- Add: `deduplicationScope` FIFO queue binding property to both channel and operation binding.
- Add: `fifoThroughputLimit` FIFO queue binding property to both channel and operation binding.
=> feat(bindings): add high throughput fifo properties

src/LEGO.AsyncAPI.Bindings/Sns/SnsChannelBinding.cs, test/LEGO.AsyncAPI.Tests/Bindings/Sns/SnsBindings_Should.cs
sns ordering property is not getting parsed due to the missing mapping.
- Fix: Added missing mapping for sns ordering property
=> fix: added missing mapping for ordering

src/LEGO.AsyncAPI.Bindings/Kafka/KafkaChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Kafka/TopicConfigurationObject.cs, src/LEGO.AsyncAPI/Models/AsyncApiConstants.cs, test/LEGO.AsyncAPI.Tests/Bindings/Kafka/KafkaBindings_Should.cs
Kafka topic configuration properties have been updated in the [asyncapi/bindings](https://github.com/asyncapi/bindings) repo. Please see the latest version [here](https://github.com/asyncapi/bindings/tree/master/kafka#topicconfiguration-object).
To address those changes I've added 4 new properties to the topic configuration object.
- Added new kafka topic configuration properties
Please let me know if you need more details about the change. Thanks!
=> feat: added new topic configuration properties

src/LEGO.AsyncAPI.Bindings/Kafka/KafkaChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Kafka/TopicConfigurationObject.cs, src/LEGO.AsyncAPI/Models/AsyncApiConstants.cs, test/LEGO.AsyncAPI.Tests/Bindings/Kafka/KafkaBindings_Should.cs
The following properties need to be updated as `long`:
- **retention.ms**
- **retention.bytes**
- **delete.retention.ms**
If you need further details about the configs you can check this documentation page: https://kafka.apache.org/documentation/#topicconfigs_retention.bytes
- Updated data types from **integer** to **long**
I have also created a PR in the **asyncapi/bindings** repo here: https://github.com/asyncapi/bindings/pull/242
=> fix: updated topic configuration data types

src/LEGO.AsyncAPI.Bindings/Kafka/KafkaChannelBinding.cs, test/LEGO.AsyncAPI.Tests/Bindings/Kafka/KafkaBindings_Should.cs
retention.ms was recently converted to long, however, I noticed in my project that a long value was being processed as null. It seems there was an integer method leftover on the KafkaChannelBinding class. This PR fixes this issue for all retention values.
- Add: Long value for testing retention.ms in the Kafka bindings test
- Replace: Replaced GetIntegerValue with GetLongValue for all long retention values in the KafkaChannelBinding
=> fix: retention values should use GetLongValue

src/LEGO.AsyncAPI/Models/Any/AsyncAPIArray.cs, src/LEGO.AsyncAPI/Models/Any/AsyncAPIObject.cs, src/LEGO.AsyncAPI/Models/Any/AsyncApiAny.cs, test/LEGO.AsyncAPI.Tests/AsyncApiAnyTests.cs, test/LEGO.AsyncAPI.Tests/AsyncApiDocumentV2Tests.cs, test/LEGO.AsyncAPI.Tests/Bindings/Sns/SnsBindings_Should.cs, test/LEGO.AsyncAPI.Tests/LEGO.AsyncAPI.Tests.csproj, test/LEGO.AsyncAPI.Tests/Models/AsyncApiAnyTests.cs
Fixes some issues with working with AsyncApiAny, figuring out the correct types etc.
Added new GetValue type methods for extracting expected values.
These use `system.text.json` to deserialize to `T` from the `JsonNode` type.
Added a static FromExtension method, to remove redundant type casting.
So instead of 
```csharp
if (TryGetValue(key, out IAsyncApiExtension extension))
{
var myType = (extension as AsyncApiAny).GetValue<MyType>();
}
```
You do
```csharp
if (TryGetValue(key, out IAsyncApiExtension extension))
{
var myType = AsyncApiAny.FromExtensionOrDefault<MyType>(extension);
}
```
Added new constructor allowing for much simpler `AsyncApiAny` initialization, utlizing `system.json.text` to figure out the JsonNode type.
- Added: `GetValue<T>()`
- Added: `GetValueOrDefault<T>()`
- …
=> feat: improve AsyncApiAny api surface.

src/LEGO.AsyncAPI.Bindings/AMQP/AMQPChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/AMQP/AMQPMessageBinding.cs, src/LEGO.AsyncAPI.Bindings/AMQP/AMQPOperationBinding.cs, src/LEGO.AsyncAPI.Bindings/AMQP/ChannelType.cs, src/LEGO.AsyncAPI.Bindings/AMQP/DeliveryMode.cs, src/LEGO.AsyncAPI.Bindings/AMQP/Exchange.cs, src/LEGO.AsyncAPI.Bindings/AMQP/ExchangeType.cs, src/LEGO.AsyncAPI.Bindings/AMQP/Queue.cs, src/LEGO.AsyncAPI.Bindings/BindingsCollection.cs, src/LEGO.AsyncAPI.Bindings/Kafka/TopicConfigurationObject.cs, src/LEGO.AsyncAPI.Readers/ParseNodes/ParseNode.cs, src/LEGO.AsyncAPI.Readers/ParseNodes/ValueNode.cs, test/LEGO.AsyncAPI.Tests/Bindings/AMQP/AMQPBindings_Should.cs
Adds AMQP bindings from https://github.com/asyncapi/bindings/blob/master/amqp/README.md
I took the liberty of making the properties optional.
- Added AMQP binding
- defaulted default values of the "OrDefault" api, to null.
=> feat(bindings): add amqp bindings

src/LEGO.AsyncAPI.Bindings/Kafka/KafkaChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Kafka/TopicConfigurationObject.cs, src/LEGO.AsyncAPI/Models/AsyncApiBindings.cs, test/LEGO.AsyncAPI.Tests/Bindings/Kafka/KafkaBindings_Should.cs
This PR adds extensions for the AsyncApiBindings dictionary, so fetching specific bindings becomes a lot easier.
So instead of having to do;
```csharp
server.bindings.TryGetValue("kafka", out var binding);
```
you can now do
```csharp
server.bindings.TryGetValue<KafkaServerBinding>(out var binding);
```
Yes it uses reflection.
- Added TryGetValue extensions.
- Fixed weird kafka namespace
- Closes #<issue-number>
=> chore: add TryGetValue extensions for bindings

Common.Build.props, src/LEGO.AsyncAPI/LEGO.AsyncAPI.csproj
This adds net 6 as TFM so that System.Text.Json can be made a conditional dependency,
- Add: NET 6 as TFM
- Change: Make System.Text.Json only a dependency on net standard 2.0
- Closes #162
=> chore: add net 6 as TFM to make STJ conditional

src/LEGO.AsyncAPI.Readers/V2/AsyncApiChannelDeserializer.cs, test/LEGO.AsyncAPI.Tests/Models/AsyncApiChannel_Should.cs
The deserializer was creating a `CreateMapWithReference`, causing the deserialized model to have a reference.
When re-serializing, the parameter was serialized as a reference, but without the component efter existing.
`CreateMapWithReference` should never have been used here.
- Added: regression test
- Changed: `CreateMapWithReference` to `CreateMap` for parameters in the channel deserializer.
=> fix: inline channel parameters should not deserialize as references

src/LEGO.AsyncAPI.Readers/AsyncApiReaderSettings.cs, src/LEGO.AsyncAPI.Readers/ParseNodes/PropertyNode.cs, src/LEGO.AsyncAPI.Readers/UnmappedMemberHandling.cs, src/LEGO.AsyncAPI.Readers/V2/AsyncApiAvroSchemaDeserializer.cs, test/LEGO.AsyncAPI.Tests/AsyncApiReaderTests.cs
Added unmapped memberhandling so you can stop errors from appearing in the diagnostics, if you have unmapped members.
- Add: unmapped member handling enum
- Closes #169
=> feat: unmapped member handling during deserialization

src/LEGO.AsyncAPI.Bindings/BindingsCollection.cs, src/LEGO.AsyncAPI.Readers/AsyncApiReaderSettings.cs
Changes bindings base collection type to be of type `ICollection` to make bindings easier to add.
=> chore(bindings): change bindings to be ICollection

src/LEGO.AsyncAPI/Services/AsyncApiReferenceResolver.cs, test/LEGO.AsyncAPI.Tests/AsyncApiReaderTests.cs
When a reference is resolved, that doesnt map to the correct type, for instance;
```yaml
asyncapi: 2.3.0
info:
title: test
version: 1.0.0
channels:
workspace:
publish:
message:
$ref: '#/components/securitySchemes/saslScram'
components:
securitySchemes:
saslScram:
type: scramSha256
description: Provide your username and password for SASL/SCRAM authentication
```
mapping a message to a securityScheme. No error will be present in the diagnostics object.
The message will simply be null. 
This PR adds a quick and dirty exception to reference resolution when casting to `T` ends with being null.
=> fix: resolving wrong reference

src/LEGO.AsyncAPI.Bindings/Sns/PrincipalObject.cs, src/LEGO.AsyncAPI.Bindings/Sns/PrincipalStar.cs, src/LEGO.AsyncAPI.Bindings/Sqs/PrincipalObject.cs, src/LEGO.AsyncAPI.Bindings/Sqs/PrincipalStar.cs
https://github.com/LEGO/AsyncAPI.NET/pull/187 was recently merged, however, the principal value properties were set as private. This was a mistake and should be made public so that they can be used after the asyncapi specs have been processed.
- Add: AWS Policy Prinicpal values made public
=> chore: make principal values public

src/LEGO.AsyncAPI.Bindings/Sns/Condition.cs, src/LEGO.AsyncAPI.Bindings/Sns/SnsChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Sns/Statement.cs, src/LEGO.AsyncAPI.Bindings/Sqs/Condition.cs, src/LEGO.AsyncAPI.Bindings/Sqs/SqsChannelBinding.cs, src/LEGO.AsyncAPI.Bindings/Sqs/SqsOperationBinding.cs, src/LEGO.AsyncAPI.Bindings/Sqs/Statement.cs, test/LEGO.AsyncAPI.Tests/Bindings/Sns/SnsBindings_Should.cs, test/LEGO.AsyncAPI.Tests/Bindings/Sqs/SqsBindings_should.cs
The value of the AWS condition is currently set to AsyncApiAny. This is too open-ended and makes it difficult for the user to parse and use the value when parsing AsyncApi files. This PR sets the structure for `condition` and makes it explicit, which will make using the value on the other side more simple.
- Update: Set an explicit value for AWS condition
N/A
=> chore: make aws condition value explicit

src/LEGO.AsyncAPI/Resource.Designer.cs, src/LEGO.AsyncAPI/Resource.resx, src/LEGO.AsyncAPI/Services/AsyncApiVisitorBase.cs, src/LEGO.AsyncAPI/Services/AsyncApiWalker.cs, src/LEGO.AsyncAPI/Validation/AsyncApiValidator.cs, src/LEGO.AsyncAPI/Validation/Rules/AsyncApiAvroRules.cs, test/LEGO.AsyncAPI.Tests/Validation/ValidationRulesetTests.cs
This pull request introduces several changes to the `LEGO.AsyncAPI` project, primarily focusing on enhancing validation capabilities and adding support for Avro schema payloads. The most important changes include adding new validation rules, updating resource strings, and extending the visitor and walker functionalities.
* Added new validation rules for `AsyncApiAvroSchemaPayload` to ensure names and symbols match specified regular expressions. (`src/LEGO.AsyncAPI/Validation/Rules/AsyncApiAvroRules.cs`)
* Introduced new resource strings for validation messages related to name and symbol regular expressions. (`src/LEGO.AsyncAPI/Resource.Designer.cs`, `src/LEGO.AsyncAPI/Resource.resx`) [[1]](diffhunk://#diff-1e9bb7d71db7e47579d02dbae6421aa98195dfcc4e08c2056a0361fec91fb9a8R107-R124) …
=> chore: add AvroValidationRule for names and symbols

src/LEGO.AsyncAPI/Models/Avro/AvroField.cs, test/LEGO.AsyncAPI.Tests/Models/AvroSchema_Should.cs
This pull request includes changes to the `SerializeV2` method in `AvroField.cs` and adds a new test case in `AvroSchema_Should.cs` to handle serialization of default null values correctly.
* [`src/LEGO.AsyncAPI/Models/Avro/AvroField.cs`](diffhunk://#diff-31d7a5e316924f57f061587f7de5f03e2b30f729e66e0b3876ac57f292d34547L70-R81): Modified the `SerializeV2` method to check if the default value is "null" and write a JSON null value accordingly.
* [`test/LEGO.AsyncAPI.Tests/Models/AvroSchema_Should.cs`](diffhunk://#diff-b6070ee9357cf3afda4b2e29278939aca7ff8d59f78b67c2786ccdfb43b5c630R13-R35): Added a new test case `Serialize_WithDefaultNull_SetJsonNull` to verify that the default null value is correctly serialized as JSON null.
=> fix: null representation for AvroField 'default' property

src/LEGO.AsyncAPI/Resource.Designer.cs, src/LEGO.AsyncAPI/Resource.resx, src/LEGO.AsyncAPI/Validation/Rules/AsyncApiDocumentRules.cs, test/LEGO.AsyncAPI.Tests/Validation/ValidationRuleTests.cs, test/LEGO.AsyncAPI.Tests/Validation/ValidationRulesetTests.cs
This pull request introduces several changes to the `LEGO.AsyncAPI` project, focusing on enhancing validation rules for channel keys and adding corresponding tests. The most important changes include adding a new validation rule to ensure channel keys are unique, updating existing regex validations, and adding new unit tests to verify the functionality.
* [`src/LEGO.AsyncAPI/Resource.Designer.cs`](diffhunk://#diff-1e9bb7d71db7e47579d02dbae6421aa98195dfcc4e08c2056a0361fec91fb9a8R63-R71): Added a new localized string `Validation_ChannelsMustBeUnique` to provide an error message when channel keys are not unique.
* [`src/LEGO.AsyncAPI/Resource.resx`](diffhunk://#diff-cda9f8a3fd7560c5f3e9e39b467b79448af0ae5c0bf66c9e36dbbd72a7203323R120-R122): Added the corresponding resource entry for …
=> chore: add channelKey validation rule

Common.Build.props, src/LEGO.AsyncAPI.Bindings/LEGO.AsyncAPI.Bindings.csproj, src/LEGO.AsyncAPI.Readers/LEGO.AsyncAPI.Readers.csproj, src/LEGO.AsyncAPI/LEGO.AsyncAPI.csproj
This pull request includes several updates to the project dependencies and target frameworks. The most important changes are the upgrade of the target framework to `net8` and the update of the `System.Text.Json` package version across multiple project files.
* [`Common.Build.props`](diffhunk://#diff-2915b440681d4b8a0f29292651453ec6dbfd3d5e46dc482682f55a814ca449f4L5-R5): Updated the `TargetFrameworks` property from `net6` to `net8`.
* [`src/LEGO.AsyncAPI.Bindings/LEGO.AsyncAPI.Bindings.csproj`](diffhunk://#diff-4ee188a81c8350bfa0d31467798dde56d83ead20806f1569dcd37c867a48e1c0R22): Added a new package reference for `System.Text.Json` version `9.0.1`.
* [`src/LEGO.AsyncAPI.Readers/LEGO.AsyncAPI.Readers.csproj`](diffhunk://#diff-052111eb4fc428ea5fa4582a88101b69dfb4cd2ef024828b8e1998ef2f673353R2 …
=> chore: upgrade from net6 to net8

src/LEGO.AsyncAPI/Writers/AsyncApiWriterExtensions.cs, test/LEGO.AsyncAPI.Tests/AsyncApiDocumentV2Tests.cs
Writing a required map should continue to writeInternal without the ability to return early on the if statement so it fails accordingly to the 'required rule'.
- Remove: Removed bug from the writer!
=> fix: dont return early for required map
